### ISSUE TITLE
[openSUSE Tumbleweed] Found test in site-packages/test/ when building from source.

### ISSUE THREAD

**Issue by kevinsmia1939** [MycroftAI/lingua-franca#178]
Hello,

I am trying to package this module for openSUSE. I found a file that went to

`/usr/lib/python3.8/site-packages/test/`

which it is not allow in SUSE,  I think they prefer to be in `site-packages/lingua_franca/test/`

I see that test folder was include in setup.py `packages=['test', 'lingua_franca', 'lingua_franca.lang'],`.
Thanks.

**Comment by ChanceNCounter** [comment]
Personal opinion:

Please don't package Python libs for your distro. Python programs will download their own libs. That's the point of pypi.

**Comment by ChanceNCounter** [comment]
Alright. Having attempted to look at the current state of pypi recommendations on including test files, I have determined that there still aren't any. Joy of joys.

Because Lingua Franca is a lib, and not executable, I think we should avoid installing the test files entirely. We can accomplish this by including them via `MANIFEST.in` but not via `setup.py`.

**Comment by kevinsmia1939** [comment]
Alright thank, will remove the test.
